# the build and test are simple, so we combine them
# test against the relased version of heasoft first, then agains the develop version
stages:
  - heasoft_release_version
  - heasoft_develop_version
  
# put common task here, and we call it later
.build_and_test_heasoftpy:
  tags:
    - heasoftpy-local-pulsar
  script:
    - export HEADAS=`ls -d /software/lheasoft/$VERSION/x86_64-pc-linux-gnu-libc$(ldd --version | grep ldd | sed 's:.*)[ ]*::')`
    - echo "\n*** Using heasoft in $HEADAS ***\n"
    - source $HEADAS/headas-init.sh
    - export PYTHON=$(gawk '/PYTHON =/ {print $3;exit}' $HEADAS/BUILD_DIR/`basename $HEADAS`*.log)
    - $PYTHON -m venv .hpy
    - source .hpy/bin/activate
    - pip install pytest
    - pip install -r requirements.txt
    - python local-build.py
    - python -m pytest


# do the release version
build-test-local-release:
  stage: heasoft_release_version
  variables:
    VERSION: release
  extends: .build_and_test_heasoftpy

# do the develop version
build-test-local-develop:
  stage: heasoft_develop_version
  variables:
    VERSION: develop
  extends: .build_and_test_heasoftpy

